name: manajet-app
region: nyc

services:
- name: web
  github:
    repo: miguellini37/manajet-app
    branch: master
    deploy_on_push: true

  dockerfile_path: Dockerfile

  http_port: 5000

  instance_count: 1
  instance_size_slug: basic-xxs

  health_check:
    http_path: /login
    initial_delay_seconds: 30
    period_seconds: 30
    timeout_seconds: 10
    success_threshold: 1
    failure_threshold: 3

  envs:
  - key: SECRET_KEY
    scope: RUN_TIME
    type: SECRET
  - key: DEBUG
    value: "False"
  - key: SESSION_COOKIE_SECURE
    value: "True"
  - key: SESSION_COOKIE_HTTPONLY
    value: "True"
  - key: SESSION_COOKIE_SAMESITE
    value: "Lax"
  - key: PERMANENT_SESSION_LIFETIME
    value: "3600"
  - key: PORT
    value: "5000"

  routes:
  - path: /

databases:
- name: db
  engine: PG
  version: "15"
  production: false  # Set to true for production (higher cost but better performance)
